### ISSUE TITLE
Nbr de Recycleur 

### ISSUE THREAD

**Issue by zegame04** [OGSteam/mod-cdr#4]
https://github.com/OGSteam/mod-cdr/blob/554771bed66b5fd07a2fa98e55b05fb66acf3466/cdr.php#L216

Bonjour =)
Le nombre de recycleur est calculer avec le nombre 20 000 de "Capacité de fret", et n'est pas mis a jour avec la recherche "Technologie hyperespace" (5% de fret en plus par niveau de recherche).

Pourrait-on imaginer de pouvoir modifier la valeur de la capacité de fret soit via : 
 - le menu "option", avec une case pour mettre a jour manuellement cette valeur
- ou avec une lecture du niveau de la "Technologie hyperespace", qui permettra de calculer le "Bonus de recherche" pour la capacité de de fret.

Merci

**Comment by darknoon29** [comment]
Hello on a même la techno du joueur en BDD. On pourrait la passer

**Comment by zegame04** [comment]
ça serait top ! ^^
